### ISSUE TITLE
Error running game

### ISSUE THREAD

**Issue by mogambro** [RaminKav/BevySurvivalGame#14]
Hello!

First off: Thanks for the  work you've put into this game. It looks lovely. Sadly I cannot run it locally to tinker a bit more, because of these issues:

First I had:

```
TRYING TO LOAD GAME
DONE LOADING
Loading prototypes...
proto "StoneWall" not ready
SPAWNING NEW DIMENSION
2024-04-15T09:18:55.396415Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/proto/worldgenerationparams.prototype.ron
Loading prototypes...
2024-04-15T09:18:55.486095Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/proto/worldgenerationparams.prototype.ron
DESPAWNING EVERYTHING!!! 0
proto "StoneWall" not ready
Loading prototypes...
2024-04-15T09:18:55.597050Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/proto/worldgenerationparams.prototype.ron
proto "StoneWall" not ready
Loading prototypes...
2024-04-15T09:18:55.612678Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/proto/worldgenerationparams.prototype.ron
READY, ENTERING GAME STATE
thread 'Compute Task Pool (10)' panicked at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/system/system_param.rs:460:17:
Resource requested by survival_rogue_like::assets::GameAssetsPlugin::load_graphics does not exist: survival_rogue_like::ImageAssets
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (10)' panicked at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60:
A system has panicked so the executor cannot continue.: RecvError
thread 'Compute Task Pool (21)' panicked at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60:
A system has panicked so the executor cannot continue.: RecvError
```

I assume you use Windows? On unix-based operating systems "WorldGenerationParams.prototype.ron" is not the same as "worldgenerationparams.prototype.ron".

The same is true for the folder `assets/textures/Player`... it's not the same as `assets/textures/player`

**I've fixed all these issues, but now I get**:

```
2024-04-15T09:51:08.989631Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling Arch Linux", kernel: "6.8.5-arch1-1", cpu: "AMD Ryzen 9 5950X 16-Core Processor", core_count: "16", memory: "62.7 GiB" }
TRYING TO LOAD GAME
DONE LOADING
Loading prototypes...
proto "StoneWall" not ready
SPAWNING NEW DIMENSION
Loading prototypes...
DESPAWNING EVERYTHING!!! 0
proto "StoneWall" not ready
Loading prototypes...
proto "StoneWall" not ready
Loading prototypes...
READY, ENTERING GAME STATE
thread 'Compute Task Pool (19)' panicked at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/system/system_param.rs:460:17:
Resource requested by survival_rogue_like::assets::GameAssetsPlugin::load_graphics does not exist: survival_rogue_like::ImageAssets
```

I am not sure what's going wrong here, as the code looks good. I am not familiar with `bevy_asset_loader` though.

**Comment by RaminKav** [comment]
Hey, sorry again for not seeing this. Let me know if it happens in the latest commit. I saw that you may have already fixed this in the fork, but if not, ill take a look.

Thanks for checking out my game!

**Comment by mogambro** [comment]
No worries, thanks for taking your time to answer!

I checked out the latest commit as of writing this and it fails with:

```

2024-05-29T15:30:39.181495Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/BevySurvivalGame/assets/textures/player/player_down.png
2024-05-29T15:30:39.183029Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling Arch Linux", kernel: "6.9.2-arch1-1", cpu: "AMD Ryzen 7 PRO 6850U with Radeon Graphics", core_count: "8", memory: "30.1 GiB" }
Loading prototypes...
proto "StoneWall" not ready
thread 'Compute Task Pool (2)' panicked at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/system/system_param.rs:460:17:
Resource requested by survival_rogue_like::world::generation::GenerationPlugin::generate_and_cache_objects does not exist: survival_rogue_like::world::dimension::GenerationSeed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (2)' panicked at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60:
A system has panicked so the executor cannot continue.: RecvError
2024-05-29T15:30:39.225594Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/BevySurvivalGame/assets/proto/worldgenerationparams.prototype.ron
```

**Comment by RaminKav** [comment]
> GenerationSeed

This is so strange... It seems there are 2 issues going on, and they seem unrelated, i think.

1) the warnings about asset paths. I'll definitely fix that, but its weird that this is happening. Im developing on an M1 Macbook Pro, so if you are on Unix as well, im confused why we get different results. I noticed you had a PR to fix these, ill take a look and get it merged in!

2) the more problematic issue here seems to be the missing resources for startup systems. This is super weird, as i dont get this on windows or mac. I'll have to think on this, but as of right now, i have no idea why this would happen. Ill ask the bevy community for input. The original one for `ImageAssets` makes no sense to me, but it didnt happen in the second error, so maybe its resolved.

The `GenerationSeed` resource error in the latest log was my bad, I broke the startup system in my latest commit that added save/load, if the user had no save_data. Its fixed now and i pushed up the commit, let me know if it loads up for you now!

**Comment by mogambro** [comment]
The latest commit runs I just don't see the player, but yeah it runs <3... thank you!

As we know, a lot of warnings:

```
2024-06-03T10:36:14.353044Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/textures/StingFly/StingFly_down.png
2024-06-03T10:36:14.353047Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/textures/FurDevil/FurDevil_down.png
LOADED UI ASSET "XPBarFrame"
2024-06-03T10:36:14.353052Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/textures/Bushling/Bushling_side.png
2024-06-03T10:36:14.353053Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/textures/Hog/Hog_side.png
2024-06-03T10:36:14.353063Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/textures/Bushling/Bushling_up.png
```

And that's again a upper/lowercase problem....

```bash

cat /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/greensapplingstage2.png
cat: /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/greensapplingstage2.png: No such file or directory
```
but 

```bash
cat /home/nerdachse/projects/game_dev/inspiration/BevySurvivalGame/assets/GreenSapplingStage2.png
PNG

IHDR�sRGB��^IDATH�J�
鴒RtW).�t�ta1>
              �b\ �0�01͟�!L2�9ۻ��kQ[�4�}                �!$�}DHW6Ͱz
܌G�;R�u�ɢ$Y2@o���$k��t�PDG���H��q(q5>��w^`+�r5�E���yrV�
��bY�0饵pmVIENDB`⏎    
```

**Comment by RaminKav** [comment]
That is super weird that you dont see the player, is it an asset issue like the others? Do you see player asset warnings too? 

Also damn what is that output at the bottom, with the weird characters? never seen that before.

Glad you got the game running though!

**Comment by mogambro** [comment]
Hey again!

No, it's not weird, I don't own a MacOS system, but I searched real quick and although it's Unix based the default filesystem seems to be case-insensitive just like Windows.

My filesystem on Linux is case sensitive, so that's the whole problem here.

`GreenSapplingStage2.png` is not the same as `greensapplingstage2.png` for my system. It is for Windows and (default) MacOS though.

The output at the end was the output of `cat` in the terminal. 

`cat` cannot render a png file, so it shows the bytes instead and my terminal seems to interpret them as utf-8. it was just a test that the file exists though!

Thanks again for your help!

**Comment by RaminKav** [comment]
Oh sorry i completely missed the `cat` at the start there, that makes a lot more sense! 

Sorry again about the case issues, i will make sure i add that to my list of things to fix. Glad you got it working! Ill be continually adding more features/fixes now that im back in the flow of things

**Comment by mogambro** [comment]
Sorry, regarding `cat`:

I didn't mean to be condescending or sound educational, I am working with so many people that don't know their way around a terminal (by occupation, not idiocy) so it was natural to me to explain it.

You have nothing to be sorry about, really. Thanks for making your efforts open source!
I am looking forward how you will upgrade to future bevy versions because `bevy_proto` is stuck at the moment!

**Comment by RaminKav** [comment]
Oh don't worry, I didnt take it like that at all! Always appreciate an opportunity to learn, regardless :)

You're welcome, I'm glad you found it useful! Im also waiting in anticipation for bevy to upstream `bevy_proto` in their `BST` stuff, i hope it makes it in with `v0.14`  so i can finally update.

The reason i stopped development for a while was because I was discouraged not being able to keep up-to-date with bevy, but I figured I can keep moving forward anyway, and update when the time comes.
